version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: serverless
    versions:
    - 2.17.0
    - 2.21.1
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: aws-sdk
    versions:
    - 2.820.0
    - 2.834.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: jest-environment-node
    versions:
    - 26.6.2
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
