language: node_js

node_js:
  - "node"
  - "lts/*"

cache: npm

# branches:
#   only:
#     - master

jobs:
  include:
    - stage: install
      name: "Install Dependencies"
      script: npm install
    - stage: test
      name: "Unit Tests + Coverage"
      script:
        - npm run test:coverage
        - echo "Report Coverage..."
        - npm run codecov
    - stage: publish
      name: "Build and publish to NPM"
      node_js: 'node'
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - echo "Building.."
          - npm run build
          - echo "Publishing to NPM..."
          - npm run semantic-release
        on:
          branch: master

stages:
  - install
  - test
  - publish
