language: node_js

node_js:
  - "node"
  - "lts/*"

cache: npm

# branches:
#   only:
#     - master

jobs:
  include:
    - stage: install
      name: "Install Dependencies"
      script: npm install
    - stage: test
      name: "Unit Tests + Coverage"
      script:
        - npm run test:coverage
        - echo "Report Coverage..."
        - npm run codecov
    - stage: publish
      name: "Publish to NPM"
      node_js: 'node'
      script: echo "Publishing to NPM..."
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run build && npm run semantic-release

stages:
  - install
  - test
  - publish
    if: branch = master
