language: node_js

node_js:
  - "node"
  - "lts/*"

cache: yarn

# branches:
#   only:
#     - master

jobs:
  include:
    - stage: install
      name: "Install Dependencies"
      script: yarn
    - stage: test
      name: "Unit Tests + Coverage"
      script:
        - yarn test:coverage
        - echo "Report Coverage..."
        - yarn codecov
    - stage: publish
      name: "Build and publish to NPM"
      node_js: 'node'
      script: skip
      deploy:
        provider: script
        # skip_cleanup: true // deprecated in preparation for dpl2 - cleanup is false by default now
        script:
          - echo "Building.."
          - yarn build:ci
          - echo "Publishing to NPM..."
          - yarn semantic-release
        on:
          branch: master

stages:
  - install
  - test
  - publish
