language: node_js

node_js:
  - "node"
  - "lts/*"

cache: npm

# branches:
#   only:
#     - master

jobs:
  include:
    - stage: install
      name: "Install Dependencies"
      script: npm install
    - stage: test
      name: "Unit Tests + Coverage"
      script:
        - npm test:coverage
        - echo "Report Coverage..."
        - npm run codecov
    - stage: publish
      name: "Publish to NPM"
      node_js: 'node'
      script: echo "Publishing to NPM..."
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
      deploy:
#        provider: npm
#        email: stefan.tertan@mysense.ai
#        api_key:
#          secure: TODO
#        on:
#          branch: master
#          tags: true
#          condition: -z $SKIP_PUBLISH
        provider: script
        skip_cleanup: true
        script: echo 'deploying to NPM'
          # npm run build && npm run semantic-release
        on:
          tags: true

stages:
  - install
  - test
  - publish
